image: golang:latest

stages:
  - lint
  - test

go_vet:
  stage: lint
  script:
    - go vet $(go list ./... | grep -v /vendor/)

go_fmt:
  stage: lint
  script:
    - go fmt $(go list ./... | grep -v /vendor/)

go_test:
  stage: test
  script:
    - go test -v -cover ./...
