global:
  resolve_timeout: 5m

route:
  receiver: "default"
  routes:
    - match:
        severity: info
      receiver: slack

    - match:
        severity: critical
      receiver: email
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 5m